package org.protege.mcp;

import java.io.InputStream;
import java.util.Properties;

/**
 * Single source of truth for the {@code protege-mcp} bundle version reported
 * over MCP (in {@code initialize.serverInfo.version} and
 * {@code server_info.version}).
 *
 * <p>
 * Resolution order:
 * <ol>
 * <li>OSGi {@code Bundle-Version} of the bundle that loaded this class, when
 * running inside an OSGi framework.</li>
 * <li>{@code /META-INF/maven/org.protege/protege-mcp/pom.properties}
 * (generated by Maven at build time) on the classpath.</li>
 * <li>{@link #FALLBACK} as a last resort.</li>
 * </ol>
 *
 * <p>
 * The resolved value is cached for the lifetime of the JVM.
 */
final class ProtegeMcpVersion {

    static final String FALLBACK = "0.0.0-unknown";

    private static final String VALUE = resolve();

    private ProtegeMcpVersion() {
    }

    /** Return the bundle version, never {@code null} or empty. */
    static String get() {
        return VALUE;
    }

    private static String resolve() {
        String osgi = readOsgiBundleVersion();
        if (isPresent(osgi)) {
            return osgi;
        }
        String maven = readMavenPomProperties();
        if (isPresent(maven)) {
            return maven;
        }
        return FALLBACK;
    }

    private static String readOsgiBundleVersion() {
        try {
            // Reflective lookup so the class is usable in plain JUnit (no OSGi runtime).
            Class<?> frameworkUtil = Class.forName("org.osgi.framework.FrameworkUtil");
            Object bundle = frameworkUtil
                    .getMethod("getBundle", Class.class)
                    .invoke(null, ProtegeMcpVersion.class);
            if (bundle == null) {
                return null;
            }
            Object version = bundle.getClass().getMethod("getVersion").invoke(bundle);
            return version == null ? null : version.toString();
        } catch (Throwable ignored) {
            return null;
        }
    }

    private static String readMavenPomProperties() {
        String resource = "/META-INF/maven/edu.stanford.protege/protege-mcp/pom.properties";
        try (InputStream in = ProtegeMcpVersion.class.getResourceAsStream(resource)) {
            if (in == null) {
                return null;
            }
            Properties props = new Properties();
            props.load(in);
            return props.getProperty("version");
        } catch (Throwable ignored) {
            return null;
        }
    }

    private static boolean isPresent(String s) {
        return s != null && !s.isEmpty() && !"0.0.0".equals(s);
    }
}
